name: Publish Studio
description: 'Package Studio into executable files and publish it'

runs:
  using: composite
  steps:
    - name: Make Studio executable and publish
      shell: bash
      run: |
        git submodule update --init --recursive
        cd psdk-binaries
        curl -s https://download.psdk.pokemonworkshop.com/binaries/${{ runner.os }}.7z -o binaries.7z
        7z x binaries.7z
        rm binaries.7z
        cd ..
        npm run publish
      env:
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Save to Github Artifact
      uses: actions/upload-artifact@v3
      with:
        name: studio_${{ env.BRANCH_NAME }}_${{ runner.os }}
        path: ./out/make
