default:
  image: ubuntu:20.04

stages:
  - test
  - build

linux-test:
  stage: test
  image: node:18
  script:
    - npm ci
    - npm test
  only:
    - develop

linux-build:
  stage: build
  when: manual
  image: node:18
  script:
    - npm ci
    - npm run build
    - npm run package
    - ls release/
  only:
    - develop

win-build:
  stage: build
  when: manual
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run build
    - npm run package
    - ls release/
  only:
    - develop
#osx-build:
#  stage: build
#  script:
#    - npm install --ignore-optional --no-lockfile
#    - npm run build
#    - npm run package
#    - ls release/
#  tags:
#    - shared-macos-amd64
#  only:
#    - develop
