import type { StudioEventCommandType } from '@modelEntities/event/command';
import { JSX } from 'react';
import type { CommandNodeProps } from '../commands/CommandNodeProps';
import { DefaultCommand } from '../commands/DefaultCommand';
import { InsertScriptCommand } from '../commands/InsertScriptCommand';
import { ShadowNode } from './ShadowNode';

export const CommandToNodes: Record<StudioEventCommandType | 'shadow_node', (props: CommandNodeProps) => JSX.Element> = {
  show_message: DefaultCommand,
  narrator_settings: DefaultCommand,
  manage_message_box: DefaultCommand,
  show_choice: DefaultCommand,
  wait_key_press: DefaultCommand,
  record_key_press: DefaultCommand,
  input_creature_name: DefaultCommand,
  input_character_name: DefaultCommand,
  ask_player_for_number: DefaultCommand,
  create_loop: DefaultCommand,
  exit_loop: DefaultCommand,
  manage_conditions: DefaultCommand,
  go_to: DefaultCommand,
  wait_for_set_time: DefaultCommand,
  stop_event_execution: DefaultCommand,
  call_event: DefaultCommand,
  trigger_event: DefaultCommand,
  change_event_parameters: DefaultCommand,
  move_event: DefaultCommand,
  teleport_event: DefaultCommand,
  teleport_player: DefaultCommand,
  wait_move_completion: DefaultCommand,
  manage_event_reappearance: DefaultCommand,
  manage_path_finding: DefaultCommand,
  manage_follow_me: DefaultCommand,
  manage_variables: DefaultCommand,
  manage_event_variables: DefaultCommand,
  manage_timer: DefaultCommand,
  change_character_name: DefaultCommand,
  start_trainer_battle: DefaultCommand,
  start_wild_encounter: DefaultCommand,
  start_scripted_battle: DefaultCommand,
  manage_random_encounters: DefaultCommand,
  manage_player_items: DefaultCommand,
  manage_player_money: DefaultCommand,
  manage_dex: DefaultCommand,
  set_active_dex: DefaultCommand,
  give_badge: DefaultCommand,
  manage_access_save_menu: DefaultCommand,
  open_save_menu: DefaultCommand,
  manage_autosave: DefaultCommand,
  force_autosave: DefaultCommand,
  force_save: DefaultCommand,
  open_scene: DefaultCommand,
  open_shop: DefaultCommand,
  open_custom_scene: DefaultCommand,
  manage_access_main_menu: DefaultCommand,
  trigger_game_over: DefaultCommand,
  return_to_title_screen: DefaultCommand,
  open_creature_shop: DefaultCommand,
  start_quest: DefaultCommand,
  display_hidden_objective: DefaultCommand,
  validate_quest_objectives: DefaultCommand,
  display_quest_progress: DefaultCommand,
  complete_quest: DefaultCommand,
  play_sound: DefaultCommand,
  stop_current_sound: DefaultCommand,
  change_default_sound: DefaultCommand,
  memorize_background_sounds: DefaultCommand,
  restore_background_sounds: DefaultCommand,
  play_creature_cry: DefaultCommand,
  change_screen_tone: DefaultCommand,
  display_animation: DefaultCommand,
  display_screen_animation: DefaultCommand,
  display_emotion: DefaultCommand,
  manage_image: DefaultCommand,
  manage_camera: DefaultCommand,
  manage_dynamic_light: DefaultCommand,
  change_weather: DefaultCommand,
  manage_map_fog: DefaultCommand,
  manage_map_panorama: DefaultCommand,
  change_battle_background: DefaultCommand,
  insert_script: InsertScriptCommand,
  shadow_node: ShadowNode,
};
