name: Package Studio
description: 'Package Studio into executable files'

runs:
  using: composite
  steps:
    - name: Make Studio executable
      shell: bash
      run: |
        git submodule update --init --recursive
        npm run make
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Save to Github Artifact
      uses: actions/upload-artifact@v3
      with:
        name: studio_${{ env.BRANCH_NAME }}_${{ runner.os }}
        path: ./out/make
