name: Package Studio
description: 'Package Studio into executable files'

runs:
  using: composite
  steps:
    # - name: Make Studio executable (PR/Develop)
    #   if: github.ref != 'refs/heads/main'
    #   shell: bash
    #   run: |
    #     npm run make
    #   env:
    #     GH_TOKEN: ${{ github.token }}

    - name: Make Studio executable (Main)
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        git submodule update --init --recursive
        cd psdk-binaries
        wget https://download.psdk.pokemonworkshop.com/binaries/{{ runner.os }}.7z
        7z x {{ runner.os }}.7z
        cd ..
        npm run make
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Save to Github Artifact
      uses: actions/upload-artifact@v3
      with:
        name: studio_${{ env.BRANCH_NAME }}_${{ runner.os }}
        path: ./out/make
