import type { StudioEventCommandCategory } from './category';
import { z } from 'zod';

export const EVENT_COMMAND_VALIDATOR = z.union([
  z.literal('show_message'),
  z.literal('narrator_settings'),
  z.literal('additional_options_message'),
  z.literal('show_choice'),
  z.literal('wait_key_press'),
  z.literal('record_key_press'),
  z.literal('input_creature_name'),
  z.literal('input_character_name'),
  z.literal('ask_player_for_number'),
  z.literal('create_loop'),
  z.literal('exit_loop'),
  z.literal('manage_conditions'),
  z.literal('go_to'),
  z.literal('wait_for_set_time'),
  z.literal('stop_event_execution'),
  z.literal('call_event'),
  z.literal('trigger_event'),
  z.literal('change_event_parameters'),
  z.literal('move_event'),
  z.literal('teleport_event'),
  z.literal('teleport_player'),
  z.literal('wait_move_completion'),
  z.literal('manage_event_reappearance'), // change the wording for manage_event_life ?
  z.literal('manage_path_finding'),
  z.literal('manage_follow_me'),
  z.literal('manage_variables'),
  z.literal('manage_event_variables'),
  z.literal('manage_timer'),
  z.literal('change_character_name'), // useless ??
  z.literal('start_trainer_battle'),
  z.literal('start_wild_encounter'),
  z.literal('start_scripted_battle'),
  z.literal('manage_random_encounters'),
  z.literal('manage_items'),
  z.literal('manage_money'),
  z.literal('manage_dex'),
  z.literal('set_active_dex'),
  z.literal('give_badge'),
  z.literal('manage_access_save_menu'),
  z.literal('open_save_menu'),
  z.literal('enable_autosave'),
  z.literal('force_autosave'),
  z.literal('force_save'),
  z.literal('open_scene'),
  z.literal('open_shop'),
  z.literal('open_custom_scene'),
  z.literal('manage_access_main_menu'),
  z.literal('trigger_game_over'),
  z.literal('return_to_title_screen'),
  z.literal('open_creature_shop'),
  z.literal('start_quest'),
  z.literal('display_hidden_objective'),
  z.literal('validate_quest_objectives'),
  z.literal('check_quest_completion'),
  z.literal('distribute_quest_rewards'),
  z.literal('play_sound'),
  z.literal('stop_current_sound'),
  z.literal('change_default_sound'),
  z.literal('memorize_background_sounds'),
  z.literal('restore_background_sounds'),
  z.literal('play_creature_cry'),
  z.literal('change_screen_tone'),
  z.literal('display_animation'),
  z.literal('display_screen_animation'),
  z.literal('display_emotion'),
  z.literal('manage_image'), // Display / Erase an image
  z.literal('move_camera'),
  z.literal('manage_dynamic_light'),
  z.literal('change_weather'),
  z.literal('manage_map_fog'),
  z.literal('manage_map_panorama'),
  z.literal('change_battle_background'),
  z.literal('insert_script'),
]);

export type StudioEventCommand = z.infer<typeof EVENT_COMMAND_VALIDATOR>;

export type EventCommandHelper = {
  commandType: StudioEventCommand;
  helper?: boolean;
  enabled?: boolean;
};

export const COMMANDS_FROM_CATEGORY: Record<StudioEventCommandCategory, EventCommandHelper[]> = {
  messages: [
    { commandType: 'show_message', enabled: true },
    { commandType: 'narrator_settings' },
    { commandType: 'additional_options_message' },
    { commandType: 'show_choice' },
  ],
  player_interactions: [
    { commandType: 'wait_key_press' },
    { commandType: 'record_key_press' },
    { commandType: 'input_creature_name' },
    { commandType: 'input_character_name' },
    { commandType: 'ask_player_for_number' },
  ],
  flow_control: [
    { commandType: 'create_loop' },
    { commandType: 'exit_loop' },
    { commandType: 'manage_conditions' },
    { commandType: 'go_to' },
    { commandType: 'wait_for_set_time' },
    { commandType: 'stop_event_execution' },
    { commandType: 'call_event', helper: true },
    { commandType: 'trigger_event' },
  ],
  movement: [
    { commandType: 'change_event_parameters' },
    { commandType: 'move_event' },
    { commandType: 'teleport_event' },
    { commandType: 'teleport_player' },
    { commandType: 'wait_move_completion' },
    { commandType: 'manage_event_reappearance' },
    { commandType: 'manage_path_finding' },
    { commandType: 'manage_follow_me' },
  ],
  game_data: [
    { commandType: 'manage_variables' },
    { commandType: 'manage_event_variables' },
    { commandType: 'manage_timer' },
    { commandType: 'change_character_name' },
  ],
  battles: [
    { commandType: 'start_trainer_battle' },
    { commandType: 'start_wild_encounter' },
    { commandType: 'start_scripted_battle' },
    { commandType: 'manage_random_encounters' },
  ],
  inventory: [
    { commandType: 'manage_items' },
    { commandType: 'manage_money' },
    { commandType: 'manage_dex' },
    { commandType: 'set_active_dex' },
    { commandType: 'give_badge' },
  ],
  save: [
    { commandType: 'manage_access_save_menu' },
    { commandType: 'open_save_menu' },
    { commandType: 'enable_autosave' },
    { commandType: 'force_autosave' },
    { commandType: 'force_save' },
  ],
  game_interfaces: [
    { commandType: 'open_scene' },
    { commandType: 'open_shop' },
    { commandType: 'open_custom_scene' },
    { commandType: 'manage_access_main_menu' },
    { commandType: 'trigger_game_over' },
    { commandType: 'return_to_title_screen' },
    { commandType: 'open_creature_shop' },
  ],
  quests: [
    { commandType: 'start_quest' },
    { commandType: 'display_hidden_objective' },
    { commandType: 'validate_quest_objectives' },
    { commandType: 'check_quest_completion' },
    { commandType: 'distribute_quest_rewards', helper: true },
  ],
  audio: [
    { commandType: 'play_sound' },
    { commandType: 'stop_current_sound' },
    { commandType: 'change_default_sound' },
    { commandType: 'memorize_background_sounds' },
    { commandType: 'restore_background_sounds' },
    { commandType: 'play_creature_cry' },
  ],
  visual_effects: [
    { commandType: 'change_screen_tone' },
    { commandType: 'display_animation' },
    { commandType: 'display_screen_animation' },
    { commandType: 'display_emotion' },
    { commandType: 'manage_image' },
    { commandType: 'move_camera' },
    { commandType: 'manage_dynamic_light' },
  ],
  visual_environment: [
    { commandType: 'change_weather' },
    { commandType: 'manage_map_fog' },
    { commandType: 'manage_map_panorama' },
    { commandType: 'change_battle_background' },
  ],
  scripting: [{ commandType: 'insert_script', enabled: true }],
};
