/* eslint global-require: off, no-console: off */

import { registerCheckDownloadNewProject } from '@src/backendTasks/checkDownloadNewProject';
import { registerCheckMapsModified } from '@src/backendTasks/checkMapsModified';
import { registerConvertRMXPEventsToStudioEvents } from '@src/backendTasks/convertRMXPEventsToStudioEvents';
import { registerConvertTiledMapToTileMetadata } from '@src/backendTasks/convertTiledMapToTileMetadata';
import { registerCopyTiledFiles } from '@src/backendTasks/copyTiledFiles';
import { registerDownloadFile } from '@src/backendTasks/downloadFile';
import { registerGeneratingMapOverview } from '@src/backendTasks/generatingMapOverview';
import { registerGetCompilationConfig } from '@src/backendTasks/getCompilationConfig';
import { registerGetFilePathsFromFolder } from '@src/backendTasks/getFilePathsFromFolder';
import { registerOpenCompilationWindow } from '@src/backendTasks/openCompilationWindow';
import { registerOpenStudioLogsFolder } from '@src/backendTasks/openStudioLogsFolder';
import { registerOpenTiled } from '@src/backendTasks/openTiled';
import { registerReadCsvFile } from '@src/backendTasks/readCsvFile';
import { registerReadMaps } from '@src/backendTasks/readMaps';
import { registerReadRMXPEvents } from '@src/backendTasks/readRMXPEvents';
import { registerRequestJson } from '@src/backendTasks/requestJson';
import { registerSaveCompilationLogs } from '@src/backendTasks/saveCompilationLogs';
import { registerSaveEventTree } from '@src/backendTasks/saveEventTree';
import { registerSaveMapInfo } from '@src/backendTasks/saveMapInfo';
import { registerSaveRMXPMapInfo } from '@src/backendTasks/saveRMXPMapInfo';
import { registerSaveTextInfos } from '@src/backendTasks/saveTextInfos';
import { registerStartCompilation } from '@src/backendTasks/startCompilation';
import { registerStartupStudioFile, startupFiles } from '@src/backendTasks/startupStudioFile';
import { registerSynchronizeLanguage } from '@src/backendTasks/synchronizeLanguage';
import { registerUpdateTextInfos } from '@src/backendTasks/updateTextInfos';
import windowManager from '@src/backendTasks/windowManager';
import { registerElectronProtocolWhenAppRead } from '@utils/electronProtocol';
import crypto from 'crypto';
import { app, BrowserWindow, ipcMain, protocol, shell } from 'electron';
import log, { FileTransport, PathVariables } from 'electron-log';
import { autoUpdater } from 'electron-updater';
import path from 'path';
import { registerChooseFile } from '../backendTasks/chooseFile';
import { registerChooseFolder } from '../backendTasks/chooseFolder';
import { registerChooseProjectFileToOpen } from '../backendTasks/chooseProjectFileToOpen';
import { registerConfigureNewProject } from '../backendTasks/configureNewProject';
import { registerCopyFile } from '../backendTasks/copyFile';
import { registerExtractNewProject } from '../backendTasks/extractNewProject';
import { registerFileExists } from '../backendTasks/fileExists';
import { registerGetStudioVersion } from '../backendTasks/getStudioVersion';
import { registerMigrateData } from '../backendTasks/migrateData';
import { registerProjectStudioFile } from '../backendTasks/projectStudioFile';
import { registerReadProjectConfigs } from '../backendTasks/readProjectConfigs';
import { registerReadProjectData } from '../backendTasks/readProjectData';
import { registerReadProjectMetadata } from '../backendTasks/readProjectMetadata';
import { registerReadProjectTexts } from '../backendTasks/readProjectTexts';
import { registerSaveProjectConfigs } from '../backendTasks/saveProjectConfigs';
import { registerSaveProjectData } from '../backendTasks/saveProjectData';
import { registerSaveProjectTexts } from '../backendTasks/saveProjectTexts';
import { registerShowItemInFolder } from '../backendTasks/showFileInFolder';
import { registerWriteProjectMetadata } from '../backendTasks/writeProjectMetadata';
import { getLastPSDKVersion } from '../services/getLastPSDKVersion';
import { getPSDKBinariesPath, getPSDKVersion } from '../services/getPSDKVersion';
import { startPSDK, startPSDKDebug, startPSDKWorldmap } from '../services/startPSDK';
import { updatePSDK } from '../services/updatePSDK';
import MenuBuilder from './menu';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

// Setup the log renderer
log.initialize({ preload: false });

const resolvePathFn = (vars: PathVariables) => {
  return path.join(vars.libraryDefaultDir, `renderer.log`);
};
const rendererLog = log.create({ logId: 'renderer' });
const fileTransport: FileTransport = <FileTransport>rendererLog.transports.file;
fileTransport.resolvePathFn = resolvePathFn;

protocol.registerSchemesAsPrivileged([
  {
    scheme: 'static',
    privileges: {
      secure: false,
      standard: false,
      corsEnabled: true,
      supportFetchAPI: false,
    },
  },
]);

const createWindow = async () => {
  registerElectronProtocolWhenAppRead();

  const mainWindow = windowManager.createWindow({
    name: 'main',
    isMain: true,
  });

  mainWindow.once('ready-to-show', () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    if (process.env.START_MINIMIZED) {
      mainWindow.minimize();
    } else {
      mainWindow.show();
      if (process.platform === 'win32') mainWindow.maximize();
      mainWindow.focus();
    }

    // When Studio is opened by clicking on project.studio file.
    const startupFile = process.argv.find((arg) => arg.endsWith('.studio'));
    if (startupFile) startupFiles.push(startupFile);
  });

  mainWindow.on('close', (event) => {
    mainWindow?.webContents.send('request-window-close');
    event.preventDefault();
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();

  // Open urls in the user's browser
  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url);
    return { action: 'deny' };
  });

  // Updater
  if (app.isPackaged) {
    autoUpdater.logger = log;
    autoUpdater.on('update-available', () => {
      mainWindow?.webContents.send('request-update-available');
    });
    autoUpdater.on('update-downloaded', () => {
      mainWindow?.webContents.send('request-update-downloaded');
    });
  }
};

/**
 * Add event listeners...
 */

app.on('window-all-closed', () => {
  // Note: We don't have to follow Darwin Convention, this is fucking stupid and unintuitive
  app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('will-quit', (event) => {
  const wins = BrowserWindow.getAllWindows();
  if (wins.length) {
    wins.forEach((win) => win.webContents.send('request-window-close'));
    event.preventDefault();
  }
});

ipcMain.handle('get-psdk-binaries-path', () => getPSDKBinariesPath());
ipcMain.handle('get-psdk-version', () => getPSDKVersion());
ipcMain.handle('get-app-version', () => app.getVersion());
ipcMain.once('studio-check-update', () => app.isPackaged && autoUpdater.checkForUpdates());
ipcMain.on('get-last-psdk-version', getLastPSDKVersion);
ipcMain.on('update-psdk', updatePSDK);
ipcMain.on('start-psdk', (_, projectPath: string) => startPSDK(projectPath));
ipcMain.on('start-psdk-debug', (_, projectPath: string) => startPSDKDebug(projectPath));
ipcMain.on('start-psdk-worldmap', (_, projectPath: string) => startPSDKWorldmap(projectPath));
ipcMain.on('external-window', (_, arg) => shell.openExternal(arg));
registerGetStudioVersion(ipcMain);
registerChooseProjectFileToOpen(ipcMain);
registerWriteProjectMetadata(ipcMain);
registerReadProjectMetadata(ipcMain);
registerReadProjectConfigs(ipcMain);
registerReadProjectData(ipcMain);
registerReadProjectTexts(ipcMain);
registerReadCsvFile(ipcMain);
registerMigrateData(ipcMain);
registerFileExists(ipcMain);
registerChooseFolder(ipcMain);
registerExtractNewProject(ipcMain);
registerConfigureNewProject(ipcMain);
registerSaveProjectData(ipcMain);
registerSaveProjectConfigs(ipcMain);
registerSaveProjectTexts(ipcMain);
registerProjectStudioFile(ipcMain);
registerChooseFile(ipcMain);
registerShowItemInFolder(ipcMain);
registerCopyFile(ipcMain);
registerUpdateTextInfos(ipcMain);
registerSaveTextInfos(ipcMain);
registerOpenStudioLogsFolder(ipcMain);
registerCheckMapsModified(ipcMain);
registerConvertTiledMapToTileMetadata(ipcMain);
registerSaveMapInfo(ipcMain);
registerSaveEventTree(ipcMain);
registerStartupStudioFile(ipcMain);
registerGetFilePathsFromFolder(ipcMain);
registerCopyTiledFiles(ipcMain);
registerSaveRMXPMapInfo(ipcMain);
registerReadMaps(ipcMain);
registerOpenTiled(ipcMain);
registerDownloadFile(ipcMain);
registerRequestJson(ipcMain);
registerCheckDownloadNewProject(ipcMain);
registerGeneratingMapOverview(ipcMain);
registerOpenCompilationWindow(ipcMain);
registerGetCompilationConfig(ipcMain);
registerStartCompilation(ipcMain);
registerSaveCompilationLogs(ipcMain);
registerSynchronizeLanguage(ipcMain);
registerReadRMXPEvents(ipcMain);
registerConvertRMXPEventsToStudioEvents(ipcMain);

ipcMain.on('get-md5-hash', (event, value: string) => (event.returnValue = crypto.createHash('md5').update(value, 'utf8').digest().toString('hex')));
app.whenReady().then(createWindow).catch(log.error);
