import type { StudioEventCommand, StudioEventCommandData, StudioEventCommandType } from '@modelEntities/event/command';
import { StudioEvent } from '@modelEntities/event/event';
import { findMultipleAvailableTextIdsEvent } from './ModelUtils';

const createShowMessageCommand = (event: StudioEvent) => {
  const ids = findMultipleAvailableTextIdsEvent(event, 0, 2, []);
  return {
    message: ids[0],
    allowSkipping: false,
    narrator: ids[1],
    nameColor: '#000000',
    showMessageBox: true,
    messageBoxPosition: 'bottom',
    messageBoxAppearance: '',
    lookAtThisEvent: false,
    lookToOtherEvent: '__undef__',
    minimap: '',
    portraits: [],
  };
};

const createShowChoiceCommand = (event: StudioEvent) => {
  const ids = findMultipleAvailableTextIdsEvent(event, 0, 3, []);
  return {
    message: ids[0],
    allowSkipping: false,
    narrator: ids[1],
    nameColor: '#000000',
    showMessageBox: true,
    messageBoxPosition: 'bottom',
    messageBoxAppearance: '',
    lookAtThisEvent: false,
    lookToOtherEvent: '__undef__',
    minimap: '',
    portraits: [],
    withMessage: true,
    choices: [ids[2]],
    defaultChoice: 0,
    resultVariable: 26,
  };
};

const insertScriptCommand = () => ({ script: '' });

const dummy = () => ({});

export const EventCommandCreation: Record<StudioEventCommandType, (event: StudioEvent) => Omit<StudioEventCommandData<StudioEventCommand>, 'type'>> =
  {
    show_message: createShowMessageCommand,
    narrator_settings: dummy,
    manage_message_box: dummy,
    show_choice: createShowChoiceCommand,
    wait_key_press: dummy,
    record_key_press: dummy,
    input_creature_name: dummy,
    input_character_name: dummy,
    ask_player_for_number: dummy,
    create_loop: dummy,
    exit_loop: dummy,
    manage_conditions: dummy,
    go_to: dummy,
    wait_for_set_time: dummy,
    stop_event_execution: dummy,
    call_event: dummy,
    trigger_event: dummy,
    change_event_parameters: dummy,
    move_event: dummy,
    teleport_event: dummy,
    teleport_player: dummy,
    wait_move_completion: dummy,
    manage_event_reappearance: dummy,
    manage_path_finding: dummy,
    manage_follow_me: dummy,
    manage_variables: dummy,
    manage_event_variables: dummy,
    manage_timer: dummy,
    change_character_name: dummy,
    start_trainer_battle: dummy,
    start_wild_encounter: dummy,
    start_scripted_battle: dummy,
    manage_random_encounters: dummy,
    manage_player_items: dummy,
    manage_player_money: dummy,
    manage_dex: dummy,
    set_active_dex: dummy,
    give_badge: dummy,
    manage_access_save_menu: dummy,
    open_save_menu: dummy,
    manage_autosave: dummy,
    force_autosave: dummy,
    force_save: dummy,
    open_scene: dummy,
    open_shop: dummy,
    open_custom_scene: dummy,
    manage_access_main_menu: dummy,
    trigger_game_over: dummy,
    return_to_title_screen: dummy,
    open_creature_shop: dummy,
    start_quest: dummy,
    display_hidden_objective: dummy,
    validate_quest_objectives: dummy,
    display_quest_progress: dummy,
    complete_quest: dummy,
    play_sound: dummy,
    stop_current_sound: dummy,
    change_default_sound: dummy,
    memorize_background_sounds: dummy,
    restore_background_sounds: dummy,
    play_creature_cry: dummy,
    change_screen_tone: dummy,
    display_animation: dummy,
    display_screen_animation: dummy,
    display_emotion: dummy,
    manage_image: dummy,
    manage_camera: dummy,
    manage_dynamic_light: dummy,
    change_weather: dummy,
    manage_map_fog: dummy,
    manage_map_panorama: dummy,
    change_battle_background: dummy,
    insert_script: insertScriptCommand,
  };
