import { IpcMainEvent } from 'electron';
import path from 'path';
import { readProjectFolder } from '@src/backendTasks/readProjectData';
import fsPromise from 'fs/promises';
import { z } from 'zod';
import { deletePSDKDatFile } from './migrateUtils';
import {
  StudioItem,
  StudioBerryData,
  StudioCookingData,
  ALL_PP_HEALING_ITEM_VALIDATOR,
  BALL_ITEM_VALIDATOR,
  CONSTANT_HEALING_ITEM_VALIDATOR,
  EV_BOOST_ITEM_VALIDATOR,
  EVENT_ITEM_VALIDATOR,
  EXP_INCREASE_ITEM_VALIDATOR,
  FLEEING_ITEM_VALIDATOR,
  HEALING_ITEM_VALIDATOR,
  LEVEL_INCREASE_ITEM_VALIDATOR,
  PP_HEALING_ITEM_VALIDATOR,
  PP_INCREASE_ITEM_VALIDATOR,
  RATE_HEALING_ITEM_VALIDATOR,
  REPEL_ITEM_VALIDATOR,
  STAT_BOOST_ITEM_VALIDATOR,
  STATUS_CONSTANT_HEALING_ITEM_VALIDATOR,
  STATUS_HEALING_ITEM_VALIDATOR,
  STATUS_RATE_HEALING_ITEM_VALIDATOR,
  STONE_ITEM_VALIDATOR,
  TECH_ITEM_VALIDATOR,
  UNKNOWN_ITEM_VALIDATOR,
} from '@modelEntities/item';
import { parseJSON } from '@utils/json/parse';
import { DbSymbol } from '@modelEntities/dbSymbol';

const PRE_MIGRATION_ITEM_VALIDATOR = z.discriminatedUnion('klass', [
  UNKNOWN_ITEM_VALIDATOR.omit({ isBerry: true }),
  HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  PP_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  ALL_PP_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  BALL_ITEM_VALIDATOR.omit({ isBerry: true }),
  CONSTANT_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  STAT_BOOST_ITEM_VALIDATOR.omit({ isBerry: true }),
  EV_BOOST_ITEM_VALIDATOR.omit({ isBerry: true }),
  EVENT_ITEM_VALIDATOR.omit({ isBerry: true }),
  FLEEING_ITEM_VALIDATOR.omit({ isBerry: true }),
  LEVEL_INCREASE_ITEM_VALIDATOR.omit({ isBerry: true }),
  EXP_INCREASE_ITEM_VALIDATOR.omit({ isBerry: true }),
  PP_INCREASE_ITEM_VALIDATOR.omit({ isBerry: true }),
  RATE_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  REPEL_ITEM_VALIDATOR.omit({ isBerry: true }),
  STATUS_CONSTANT_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  STATUS_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  STATUS_RATE_HEALING_ITEM_VALIDATOR.omit({ isBerry: true }),
  STONE_ITEM_VALIDATOR.omit({ isBerry: true }),
  TECH_ITEM_VALIDATOR.omit({ isBerry: true }),
]);
type StudioItemDataBeforeMigration = z.infer<typeof PRE_MIGRATION_ITEM_VALIDATOR>;

// These Records are very large, you should collapse them instead of scrolling 1300 lines
const berriesData: Record<string, StudioBerryData> = {
  cheri_berry: {
    size: 2.0,
    firmness: 'soft',
    minYield: 2,
    maxYield: 5,
    growth: 12,
    drainRate: 7,
    naturalGiftType: 'fire' as DbSymbol,
    naturalGiftPower: 80,
  },
  chesto_berry: {
    size: 8.0,
    firmness: 'super_hard',
    minYield: 2,
    maxYield: 5,
    growth: 12,
    drainRate: 7,
    naturalGiftType: 'water' as DbSymbol,
    naturalGiftPower: 80,
  },
  pecha_berry: {
    size: 4.0,
    firmness: 'very_soft',
    minYield: 2,
    maxYield: 5,
    growth: 12,
    drainRate: 7,
    naturalGiftType: 'electric' as DbSymbol,
    naturalGiftPower: 80,
  },
  rawst_berry: {
    size: 3.2,
    firmness: 'hard',
    minYield: 2,
    maxYield: 5,
    growth: 12,
    drainRate: 7,
    naturalGiftType: 'grass' as DbSymbol,
    naturalGiftPower: 80,
  },
  aspear_berry: {
    size: 5.0,
    firmness: 'super_hard',
    minYield: 2,
    maxYield: 5,
    growth: 12,
    drainRate: 7,
    naturalGiftType: 'ice' as DbSymbol,
    naturalGiftPower: 80,
  },
  leppa_berry: {
    size: 2.8,
    firmness: 'very_hard',
    minYield: 2,
    maxYield: 5,
    growth: 16,
    drainRate: 7,
    naturalGiftType: 'fighting' as DbSymbol,
    naturalGiftPower: 80,
  },
  oran_berry: {
    size: 3.5,
    firmness: 'super_hard',
    minYield: 2,
    maxYield: 5,
    growth: 16,
    drainRate: 7,
    naturalGiftType: 'poison' as DbSymbol,
    naturalGiftPower: 80,
  },
  persim_berry: {
    size: 4.7,
    firmness: 'hard',
    minYield: 2,
    maxYield: 5,
    growth: 16,
    drainRate: 7,
    naturalGiftType: 'ground' as DbSymbol,
    naturalGiftPower: 80,
  },
  lum_berry: {
    size: 3.4,
    firmness: 'super_hard',
    minYield: 2,
    maxYield: 5,
    growth: 48,
    drainRate: 13,
    naturalGiftType: 'flying' as DbSymbol,
    naturalGiftPower: 80,
  },
  sitrus_berry: {
    size: 9.5,
    firmness: 'very_hard',
    minYield: 2,
    maxYield: 5,
    growth: 32,
    drainRate: 15,
    naturalGiftType: 'psychic' as DbSymbol,
    naturalGiftPower: 80,
  },
  figy_berry: {
    size: 10.0,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 20,
    drainRate: 10,
    naturalGiftType: 'bug' as DbSymbol,
    naturalGiftPower: 80,
  },
  wiki_berry: {
    size: 11.5,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 20,
    drainRate: 10,
    naturalGiftType: 'rock' as DbSymbol,
    naturalGiftPower: 80,
  },
  mago_berry: {
    size: 12.6,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 20,
    drainRate: 10,
    naturalGiftType: 'ghost' as DbSymbol,
    naturalGiftPower: 80,
  },
  aguav_berry: {
    size: 6.4,
    firmness: 'super_hard',
    minYield: 1,
    maxYield: 5,
    growth: 20,
    drainRate: 10,
    naturalGiftType: 'dragon' as DbSymbol,
    naturalGiftPower: 80,
  },
  iapapa_berry: {
    size: 22.3,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 20,
    drainRate: 10,
    naturalGiftType: 'dark' as DbSymbol,
    naturalGiftPower: 80,
  },
  razz_berry: {
    size: 12.0,
    firmness: 'very_hard',
    minYield: 2,
    maxYield: 10,
    growth: 8,
    drainRate: 3,
    naturalGiftType: 'steel' as DbSymbol,
    naturalGiftPower: 80,
  },
  bluk_berry: {
    size: 10.8,
    firmness: 'soft',
    minYield: 2,
    maxYield: 10,
    growth: 8,
    drainRate: 3,
    naturalGiftType: 'fire' as DbSymbol,
    naturalGiftPower: 90,
  },
  nanab_berry: {
    size: 7.7,
    firmness: 'very_hard',
    minYield: 2,
    maxYield: 10,
    growth: 8,
    drainRate: 3,
    naturalGiftType: 'water' as DbSymbol,
    naturalGiftPower: 90,
  },
  wepear_berry: {
    size: 7.4,
    firmness: 'super_hard',
    minYield: 2,
    maxYield: 10,
    growth: 8,
    drainRate: 3,
    naturalGiftType: 'electric' as DbSymbol,
    naturalGiftPower: 90,
  },
  pinap_berry: {
    size: 8.0,
    firmness: 'hard',
    minYield: 2,
    maxYield: 10,
    growth: 8,
    drainRate: 3,
    naturalGiftType: 'grass' as DbSymbol,
    naturalGiftPower: 90,
  },
  pomeg_berry: {
    size: 13.5,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 32,
    drainRate: 13,
    naturalGiftType: 'ice' as DbSymbol,
    naturalGiftPower: 90,
  },
  kelpsy_berry: {
    size: 15.0,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 32,
    drainRate: 13,
    naturalGiftType: 'fighting' as DbSymbol,
    naturalGiftPower: 90,
  },
  qualot_berry: {
    size: 11.0,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 32,
    drainRate: 13,
    naturalGiftType: 'poison' as DbSymbol,
    naturalGiftPower: 90,
  },
  hondew_berry: {
    size: 16.2,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 32,
    drainRate: 13,
    naturalGiftType: 'ground' as DbSymbol,
    naturalGiftPower: 90,
  },
  grepa_berry: {
    size: 14.9,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 32,
    drainRate: 13,
    naturalGiftType: 'flying' as DbSymbol,
    naturalGiftPower: 90,
  },
  tamato_berry: {
    size: 20.0,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 32,
    drainRate: 13,
    naturalGiftType: 'psychic' as DbSymbol,
    naturalGiftPower: 90,
  },
  cornn_berry: {
    size: 7.5,
    firmness: 'hard',
    minYield: 2,
    maxYield: 10,
    growth: 24,
    drainRate: 10,
    naturalGiftType: 'bug' as DbSymbol,
    naturalGiftPower: 90,
  },
  magost_berry: {
    size: 14.0,
    firmness: 'hard',
    minYield: 2,
    maxYield: 10,
    growth: 24,
    drainRate: 10,
    naturalGiftType: 'rock' as DbSymbol,
    naturalGiftPower: 90,
  },
  rabuta_berry: {
    size: 22.6,
    firmness: 'soft',
    minYield: 2,
    maxYield: 10,
    growth: 24,
    drainRate: 10,
    naturalGiftType: 'ghost' as DbSymbol,
    naturalGiftPower: 90,
  },
  nomel_berry: {
    size: 28.5,
    firmness: 'super_hard',
    minYield: 2,
    maxYield: 10,
    growth: 24,
    drainRate: 10,
    naturalGiftType: 'dragon' as DbSymbol,
    naturalGiftPower: 90,
  },
  spelon_berry: {
    size: 13.3,
    firmness: 'soft',
    minYield: 2,
    maxYield: 15,
    growth: 60,
    drainRate: 13,
    naturalGiftType: 'dark' as DbSymbol,
    naturalGiftPower: 90,
  },
  pamtre_berry: {
    size: 24.4,
    firmness: 'very_soft',
    minYield: 3,
    maxYield: 15,
    growth: 60,
    drainRate: 13,
    naturalGiftType: 'steel' as DbSymbol,
    naturalGiftPower: 90,
  },
  watmel_berry: {
    size: 25.0,
    firmness: 'soft',
    minYield: 2,
    maxYield: 15,
    growth: 60,
    drainRate: 13,
    naturalGiftType: 'fire' as DbSymbol,
    naturalGiftPower: 100,
  },
  durin_berry: {
    size: 28.0,
    firmness: 'hard',
    minYield: 2,
    maxYield: 15,
    growth: 60,
    drainRate: 13,
    naturalGiftType: 'water' as DbSymbol,
    naturalGiftPower: 100,
  },
  belue_berry: {
    size: 30.0,
    firmness: 'very_soft',
    minYield: 2,
    maxYield: 15,
    growth: 60,
    drainRate: 13,
    naturalGiftType: 'electric' as DbSymbol,
    naturalGiftPower: 100,
  },
  occa_berry: {
    size: 9.0,
    firmness: 'super_hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'fire' as DbSymbol,
    naturalGiftPower: 80,
  },
  passho_berry: {
    size: 3.3,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'water' as DbSymbol,
    naturalGiftPower: 80,
  },
  wacan_berry: {
    size: 25.0,
    firmness: 'very_soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'electric' as DbSymbol,
    naturalGiftPower: 80,
  },
  rindo_berry: {
    size: 15.6,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'grass' as DbSymbol,
    naturalGiftPower: 80,
  },
  yache_berry: {
    size: 13.5,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'ice' as DbSymbol,
    naturalGiftPower: 80,
  },
  chople_berry: {
    size: 7.7,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'fighting' as DbSymbol,
    naturalGiftPower: 80,
  },
  kebia_berry: {
    size: 9.0,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'poison' as DbSymbol,
    naturalGiftPower: 80,
  },
  shuca_berry: {
    size: 4.2,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'ground' as DbSymbol,
    naturalGiftPower: 80,
  },
  coba_berry: {
    size: 27.8,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'flying' as DbSymbol,
    naturalGiftPower: 80,
  },
  payapa_berry: {
    size: 25.2,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'psychic' as DbSymbol,
    naturalGiftPower: 80,
  },
  tanga_berry: {
    size: 4.2,
    firmness: 'very_soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'bug' as DbSymbol,
    naturalGiftPower: 80,
  },
  charti_berry: {
    size: 2.8,
    firmness: 'very_soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'rock' as DbSymbol,
    naturalGiftPower: 80,
  },
  kasib_berry: {
    size: 14.4,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'ghost' as DbSymbol,
    naturalGiftPower: 80,
  },
  haban_berry: {
    size: 2.3,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'dragon' as DbSymbol,
    naturalGiftPower: 80,
  },
  colbur_berry: {
    size: 3.9,
    firmness: 'super_hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'dark' as DbSymbol,
    naturalGiftPower: 80,
  },
  babiri_berry: {
    size: 26.5,
    firmness: 'super_hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'steel' as DbSymbol,
    naturalGiftPower: 80,
  },
  chilan_berry: {
    size: 3.4,
    firmness: 'very_soft',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'normal' as DbSymbol,
    naturalGiftPower: 80,
  },
  liechi_berry: {
    size: 11.1,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'grass' as DbSymbol,
    naturalGiftPower: 100,
  },
  ganlon_berry: {
    size: 3.3,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'ice' as DbSymbol,
    naturalGiftPower: 100,
  },
  salac_berry: {
    size: 9.5,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'fighting' as DbSymbol,
    naturalGiftPower: 100,
  },
  petaya_berry: {
    size: 23.7,
    firmness: 'very_hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'poison' as DbSymbol,
    naturalGiftPower: 100,
  },
  apicot_berry: {
    size: 7.5,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'ground' as DbSymbol,
    naturalGiftPower: 100,
  },
  lansat_berry: {
    size: 9.7,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'flying' as DbSymbol,
    naturalGiftPower: 100,
  },
  starf_berry: {
    size: 15.3,
    firmness: 'super_hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 25,
    naturalGiftType: 'psychic' as DbSymbol,
    naturalGiftPower: 100,
  },
  enigma_berry: {
    size: 15.5,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 15,
    naturalGiftType: 'bug' as DbSymbol,
    naturalGiftPower: 100,
  },
  micle_berry: {
    size: 4.1,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 15,
    naturalGiftType: 'rock' as DbSymbol,
    naturalGiftPower: 100,
  },
  custap_berry: {
    size: 26.7,
    firmness: 'super_hard',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 15,
    naturalGiftType: 'ghost' as DbSymbol,
    naturalGiftPower: 100,
  },
  jaboca_berry: {
    size: 3.3,
    firmness: 'soft',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 15,
    naturalGiftType: 'dragon' as DbSymbol,
    naturalGiftPower: 100,
  },
  rowap_berry: {
    size: 5.2,
    firmness: 'very_soft',
    minYield: 1,
    maxYield: 5,
    growth: 96,
    drainRate: 15,
    naturalGiftType: 'dark' as DbSymbol,
    naturalGiftPower: 100,
  },
  roseli_berry: {
    size: 3.5,
    firmness: 'hard',
    minYield: 1,
    maxYield: 5,
    growth: 72,
    drainRate: 17,
    naturalGiftType: 'fairy' as DbSymbol,
    naturalGiftPower: 80,
  },
  kee_berry: {
    size: 5.0,
    firmness: 'hard',
    minYield: 1,
    maxYield: 10,
    growth: 96,
    drainRate: 17,
    naturalGiftType: 'fairy' as DbSymbol,
    naturalGiftPower: 100,
  },
  maranga_berry: {
    size: 5.0,
    firmness: 'hard',
    minYield: 1,
    maxYield: 10,
    growth: 96,
    drainRate: 17,
    naturalGiftType: 'dark' as DbSymbol,
    naturalGiftPower: 100,
  },
};

const cookingsData: Record<string, StudioCookingData> = {
  cheri_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  chesto_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  pecha_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  rawst_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  aspear_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  leppa_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 10,
    sourFlavor: 10,
  },
  oran_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 10,
  },
  persim_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  lum_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 10,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  sitrus_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 10,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  figy_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 15,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  wiki_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 15,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  mago_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 15,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  aguav_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 15,
    sourFlavor: 0,
  },
  iapapa_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 10,
    smoothness: 25,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 15,
  },
  razz_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  bluk_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  nanab_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  wepear_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 10,
  },
  pinap_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 10,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  pomeg_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  kelpsy_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 10,
  },
  qualot_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  hondew_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  grepa_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 25,
    smoothness: 20,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  tamato_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 25,
    smoothness: 30,
    spicyFlavor: 20,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  cornn_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 25,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 20,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  magost_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 25,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 20,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  rabuta_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 25,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 20,
    sourFlavor: 10,
  },
  nomel_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 25,
    smoothness: 30,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 20,
  },
  spelon_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 25,
    smoothness: 35,
    spicyFlavor: 30,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  pamtre_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 25,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 30,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  watmel_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 25,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 30,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  durin_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 25,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 30,
    sourFlavor: 10,
  },
  belue_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 25,
    smoothness: 35,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 30,
  },
  occa_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 15,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  passho_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 15,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  wacan_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 15,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  rindo_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 15,
    sourFlavor: 0,
  },
  yache_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 15,
  },
  chople_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 15,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  kebia_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 15,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  shuca_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 15,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  coba_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 15,
    sourFlavor: 0,
  },
  payapa_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 50,
    smoothness: 30,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 15,
  },
  tanga_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 20,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 10,
  },
  charti_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 10,
    dryFlavor: 20,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  kasib_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 10,
    sweetFlavor: 20,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  haban_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 10,
    bitterFlavor: 20,
    sourFlavor: 0,
  },
  colbur_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 10,
    sourFlavor: 20,
  },
  babiri_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 25,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  chilan_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 25,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  liechi_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 66,
    smoothness: 40,
    spicyFlavor: 30,
    dryFlavor: 10,
    sweetFlavor: 30,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  ganlon_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 66,
    smoothness: 40,
    spicyFlavor: 0,
    dryFlavor: 30,
    sweetFlavor: 10,
    bitterFlavor: 30,
    sourFlavor: 0,
  },
  salac_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 66,
    smoothness: 40,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 30,
    bitterFlavor: 10,
    sourFlavor: 30,
  },
  petaya_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 66,
    smoothness: 40,
    spicyFlavor: 30,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 30,
    sourFlavor: 10,
  },
  apicot_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 66,
    smoothness: 40,
    spicyFlavor: 10,
    dryFlavor: 30,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 30,
  },
  lansat_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 100,
    smoothness: 50,
    spicyFlavor: 30,
    dryFlavor: 10,
    sweetFlavor: 30,
    bitterFlavor: 10,
    sourFlavor: 30,
  },
  starf_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 100,
    smoothness: 50,
    spicyFlavor: 30,
    dryFlavor: 10,
    sweetFlavor: 30,
    bitterFlavor: 10,
    sourFlavor: 30,
  },
  enigma_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 75,
    smoothness: 60,
    spicyFlavor: 40,
    dryFlavor: 10,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  micle_berry: {
    pokeblockColor: 'green',
    betterPokeblockChance: 75,
    smoothness: 60,
    spicyFlavor: 0,
    dryFlavor: 40,
    sweetFlavor: 10,
    bitterFlavor: 0,
    sourFlavor: 0,
  },
  custap_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 75,
    smoothness: 60,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 40,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  jaboca_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 75,
    smoothness: 60,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 40,
    sourFlavor: 10,
  },
  rowap_berry: {
    pokeblockColor: 'blue',
    betterPokeblockChance: 75,
    smoothness: 60,
    spicyFlavor: 10,
    dryFlavor: 0,
    sweetFlavor: 0,
    bitterFlavor: 0,
    sourFlavor: 40,
  },
  roseli_berry: {
    pokeblockColor: 'red',
    betterPokeblockChance: 50,
    smoothness: 35,
    spicyFlavor: 0,
    dryFlavor: 0,
    sweetFlavor: 25,
    bitterFlavor: 10,
    sourFlavor: 0,
  },
  kee_berry: {
    pokeblockColor: 'pink',
    betterPokeblockChance: 66,
    smoothness: 50,
    spicyFlavor: 30,
    dryFlavor: 30,
    sweetFlavor: 10,
    bitterFlavor: 10,
    sourFlavor: 10,
  },
  maranga_berry: {
    pokeblockColor: 'yellow',
    betterPokeblockChance: 66,
    smoothness: 50,
    spicyFlavor: 10,
    dryFlavor: 10,
    sweetFlavor: 30,
    bitterFlavor: 30,
    sourFlavor: 10,
  },
};

const addParameter = (item: StudioItemDataBeforeMigration): StudioItem => {
  if (item.dbSymbol in berriesData) {
    return {
      ...item,
      isBerry: true,
      berryData: berriesData[item.dbSymbol],
      cookingData: cookingsData[item.dbSymbol],
    };
  } else {
    return {
      ...item,
      isBerry: false,
    };
  }
};

export const addBerryAndCookingDataToItems = async (_: IpcMainEvent, projectPath: string) => {
  deletePSDKDatFile(projectPath);

  const items = await readProjectFolder(projectPath, 'items');
  await items.reduce(async (lastPromise, item) => {
    await lastPromise;
    const itemParsed = PRE_MIGRATION_ITEM_VALIDATOR.safeParse(parseJSON<StudioItem>(item.data, item.filename));
    if (itemParsed.success) {
      const newItem = addParameter(itemParsed.data);
      return fsPromise.writeFile(path.join(projectPath, 'Data/Studio/items', `${newItem.dbSymbol}.json`), JSON.stringify(newItem, null, 2));
    }
  }, Promise.resolve());
};
