import type { StudioEventCommand } from '@modelEntities/event/command';
import type { EventNodeProps } from '../nodeEditor/EventNodeProps';
import { BasicNode } from '../nodeEditor/BasicNode';
import { ShadowNode } from '../nodeEditor/ShadowNode';
import { InsertScriptNode } from '../nodeEditor/InsertScriptNode';

export const CommandNodes: Record<StudioEventCommand | 'shadow_node', (props: EventNodeProps) => JSX.Element> = {
  show_message: BasicNode,
  narrator_settings: BasicNode,
  manage_message_box: BasicNode,
  show_choice: BasicNode,
  wait_key_press: BasicNode,
  record_key_press: BasicNode,
  input_creature_name: BasicNode,
  input_character_name: BasicNode,
  ask_player_for_number: BasicNode,
  create_loop: BasicNode,
  exit_loop: BasicNode,
  manage_conditions: BasicNode,
  go_to: BasicNode,
  wait_for_set_time: BasicNode,
  stop_event_execution: BasicNode,
  call_event: BasicNode,
  trigger_event: BasicNode,
  change_event_parameters: BasicNode,
  move_event: BasicNode,
  teleport_event: BasicNode,
  teleport_player: BasicNode,
  wait_move_completion: BasicNode,
  manage_event_reappearance: BasicNode,
  manage_path_finding: BasicNode,
  manage_follow_me: BasicNode,
  manage_variables: BasicNode,
  manage_event_variables: BasicNode,
  manage_timer: BasicNode,
  change_character_name: BasicNode,
  start_trainer_battle: BasicNode,
  start_wild_encounter: BasicNode,
  start_scripted_battle: BasicNode,
  manage_random_encounters: BasicNode,
  manage_player_items: BasicNode,
  manage_player_money: BasicNode,
  manage_dex: BasicNode,
  set_active_dex: BasicNode,
  give_badge: BasicNode,
  manage_access_save_menu: BasicNode,
  open_save_menu: BasicNode,
  manage_autosave: BasicNode,
  force_autosave: BasicNode,
  force_save: BasicNode,
  open_scene: BasicNode,
  open_shop: BasicNode,
  open_custom_scene: BasicNode,
  manage_access_main_menu: BasicNode,
  trigger_game_over: BasicNode,
  return_to_title_screen: BasicNode,
  open_creature_shop: BasicNode,
  start_quest: BasicNode,
  display_hidden_objective: BasicNode,
  validate_quest_objectives: BasicNode,
  display_quest_progress: BasicNode,
  complete_quest: BasicNode,
  play_sound: BasicNode,
  stop_current_sound: BasicNode,
  change_default_sound: BasicNode,
  memorize_background_sounds: BasicNode,
  restore_background_sounds: BasicNode,
  play_creature_cry: BasicNode,
  change_screen_tone: BasicNode,
  display_animation: BasicNode,
  display_screen_animation: BasicNode,
  display_emotion: BasicNode,
  manage_image: BasicNode,
  manage_camera: BasicNode,
  manage_dynamic_light: BasicNode,
  change_weather: BasicNode,
  manage_map_fog: BasicNode,
  manage_map_panorama: BasicNode,
  change_battle_background: BasicNode,
  insert_script: InsertScriptNode,
  shadow_node: ShadowNode,
};
