name: Production - CI Build

on:
  workflow_dispatch:
    inputs:
      force_build_node_module:
        description: 'Force build node_modules'
        type: boolean
        default: true
        required: true

jobs:
  build:
    name: Build Studio
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7
      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          force_build_node_module: ${{ inputs.force_build_node_module || false }}

      - name: Publish Studio
        uses: ./.github/actions/publish_studio
